/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newspaperdelivery;

import javax.swing.JOptionPane;

/**
 *
 * @author kedarkanel
 */
public class Newspaper extends javax.swing.JFrame {

    /**
     * Creates new form Newspaper
     */
    public Newspaper() {
        initComponents();
        this.daysPanel.setVisible(false);
        this.daysPanel1.setVisible(false);
        this.daysPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kpCheckBox = new javax.swing.JCheckBox();
        klCheckBox = new javax.swing.JCheckBox();
        hsCheckBox = new javax.swing.JCheckBox();
        daysPanel = new javax.swing.JPanel();
        sunCheckBox1 = new javax.swing.JCheckBox();
        monCheckBox1 = new javax.swing.JCheckBox();
        tueCheckBox1 = new javax.swing.JCheckBox();
        daysPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        wedCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        daysPanel2 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kpCheckBox.setText("Keskipohjanmaa");
        kpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpCheckBoxActionPerformed(evt);
            }
        });

        klCheckBox.setText("Kokkola Lehti");
        klCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klCheckBoxActionPerformed(evt);
            }
        });

        hsCheckBox.setText("Helsingin Sanomat");
        hsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsCheckBoxActionPerformed(evt);
            }
        });

        daysPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        sunCheckBox1.setText("Sunday");

        monCheckBox1.setText("Monday");

        tueCheckBox1.setText("Tuesday");

        javax.swing.GroupLayout daysPanelLayout = new javax.swing.GroupLayout(daysPanel);
        daysPanel.setLayout(daysPanelLayout);
        daysPanelLayout.setHorizontalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sunCheckBox1)
                    .addComponent(monCheckBox1)
                    .addComponent(tueCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        daysPanelLayout.setVerticalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sunCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tueCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        daysPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jCheckBox1.setText("Tuesday");

        wedCheckBox1.setText("Wednesday");

        jCheckBox5.setText("Thursday");

        javax.swing.GroupLayout daysPanel1Layout = new javax.swing.GroupLayout(daysPanel1);
        daysPanel1.setLayout(daysPanel1Layout);
        daysPanel1Layout.setHorizontalGroup(
            daysPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daysPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(wedCheckBox1)
                    .addComponent(jCheckBox5))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        daysPanel1Layout.setVerticalGroup(
            daysPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wedCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        daysPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jCheckBox2.setText("Sunday");

        jCheckBox3.setText("Monday");

        jCheckBox4.setText("Tuesday");

        javax.swing.GroupLayout daysPanel2Layout = new javax.swing.GroupLayout(daysPanel2);
        daysPanel2.setLayout(daysPanel2Layout);
        daysPanel2Layout.setHorizontalGroup(
            daysPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daysPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        daysPanel2Layout.setVerticalGroup(
            daysPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kpCheckBox)
                            .addComponent(klCheckBox)
                            .addComponent(hsCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(daysPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(daysPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(daysPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backButton)
                        .addGap(31, 31, 31)
                        .addComponent(addButton)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kpCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daysPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(klCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daysPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsCheckBox)
                .addGap(18, 18, 18)
                .addComponent(daysPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(addButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpCheckBoxActionPerformed
        // TODO add your handling code here: 
        //position x=-32715 y=-32688
        
        if(this.kpCheckBox.isSelected()){
            this.daysPanel1.setVisible(false);
            this.daysPanel2.setVisible(false);
            this.daysPanel.setVisible(true);
            //this.daysPanel.setBounds(-32715, -32688, 106, 23);
        }
        else if(!this.kpCheckBox.isSelected()){
            this.daysPanel.setVisible(false);
            //this.sunCheckBox.setVisible(false);
        } else {
        }
    }//GEN-LAST:event_kpCheckBoxActionPerformed

    private void klCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klCheckBoxActionPerformed
        // TODO add your handling code here:
        if(this.klCheckBox.isSelected()){
            this.daysPanel.setVisible(false);
            this.daysPanel2.setVisible(false);

            this.daysPanel1.setVisible(true);
            //this.daysPanel.setBounds(-32715, -32688, 106, 23);
        }
        else if(!this.klCheckBox.isSelected()){
            this.daysPanel1.setVisible(false);

            //this.sunCheckBox.setVisible(false);
        } else {
        }
    }//GEN-LAST:event_klCheckBoxActionPerformed

    private void hsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsCheckBoxActionPerformed
        if(this.hsCheckBox.isSelected()){  
            this.daysPanel.setVisible(false);
            this.daysPanel1.setVisible(false);
            this.daysPanel2.setVisible(true);

            //this.daysPanel.setBounds(-32715, -32688, 106, 23);
        }
        else if(!this.hsCheckBox.isSelected()){
            this.daysPanel2.setVisible(false);

            //this.sunCheckBox.setVisible(false);
        } else {
        }    }//GEN-LAST:event_hsCheckBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new AddSuscriber().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(this.sunCheckBox1.isSelected()){ sunday1="yes"; }
        if(this.monCheckBox1.isSelected()){ monday1="yes"; }
        
        this.addDeliveryDatabase.addDelivery(100, sunday1, monday1, tuesday1, sunday1, thursday1, friday1, sunday1);
        
       JOptionPane.showMessageDialog(null, "Suscriber Added Successfully.");
       new Home().setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_addButtonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newspaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newspaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newspaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newspaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newspaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel daysPanel;
    private javax.swing.JPanel daysPanel1;
    private javax.swing.JPanel daysPanel2;
    private javax.swing.JCheckBox hsCheckBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox klCheckBox;
    private javax.swing.JCheckBox kpCheckBox;
    private javax.swing.JCheckBox monCheckBox1;
    private javax.swing.JCheckBox sunCheckBox1;
    private javax.swing.JCheckBox tueCheckBox1;
    private javax.swing.JCheckBox wedCheckBox1;
    // End of variables declaration//GEN-END:variables
private String sunday1 = "no";
private String monday1="no";
private String tuesday1="no";
private String wednesday1="no";
private String thursday1="no";
private String friday1="no";
private String saturday1="no";
 private final DatabaseConnector addDeliveryDatabase = new DatabaseConnector();


}
